export const playersSeed = [
  { name: "Alisson", team: "Liverpool", position: "Goalkeeper" },
  { name: "Ederson", team: "Manchester City", position: "Goalkeeper" },
  { name: "Bento", team: "Al Nassr", position: "Goalkeeper" },
  { name: "Weverton", team: "Palmeiras", position: "Goalkeeper" },
  { name: "John", team: "Botafogo", position: "Goalkeeper" },
  { name: "Hugo Souza", team: "Corinthians", position: "Goalkeeper" },
  { name: "Danilo", team: "Flamengo", position: "Defender" },
  { name: "Vanderson", team: "Monaco", position: "Defender" },
  { name: "Yan Couto", team: "Borussia Dortmund", position: "Defender" },
  { name: "Marquinhos", team: "Paris Saint-Germain", position: "Defender" },
  { name: "Gabriel Magalhaes", team: "Arsenal", position: "Defender" },
  { name: "Bremer", team: "Juventus", position: "Defender" },
  { name: "Murillo", team: "Nottingham Forest", position: "Defender" },
  { name: "Eder Militao", team: "Real Madrid", position: "Defender" },
  { name: "Guilherme Arana", team: "Atletico Mineiro", position: "Defender" },
  { name: "Wendell", team: "Porto", position: "Defender" },
  { name: "Carlos Augusto", team: "Inter", position: "Defender" },
  { name: "Beraldo", team: "Paris Saint-Germain", position: "Defender" },
  { name: "Nino", team: "Zenit", position: "Defender" },
  { name: "Fabricio Bruno", team: "Cruzeiro", position: "Defender" },
  { name: "Leo Pereira", team: "Flamengo", position: "Defender" },
  { name: "Alex Sandro", team: "Flamengo", position: "Defender" },
  { name: "Caio Henrique", team: "Monaco", position: "Defender" },
  { name: "Renan Lodi", team: "Al Hilal", position: "Defender" },
  { name: "Emerson Royal", team: "AC Milan", position: "Defender" },
  { name: "Dodo", team: "Fiorentina", position: "Defender" },
  { name: "Alex Telles", team: "Botafogo", position: "Defender" },
  { name: "Thiago Silva", team: "Fluminense", position: "Defender" },
  { name: "Kaiki", team: "Cruzeiro", position: "Defender" },
  { name: "Ayrton Lucas", team: "Flamengo", position: "Defender" },
  { name: "Roger Ibanez", team: "Al Ahli", position: "Defender" },
  { name: "Douglas Santos", team: "Zenit", position: "Defender" },
  { name: "Alexsandro", team: "Lille", position: "Defender" },
  { name: "Joao Gomes", team: "Wolverhampton", position: "Midfielder" },
  { name: "Bruno Guimaraes", team: "Newcastle United", position: "Midfielder" },
  { name: "Douglas Luiz", team: "Juventus", position: "Midfielder" },
  { name: "Andre", team: "Wolverhampton", position: "Midfielder" },
  { name: "Andrey Santos", team: "Chelsea", position: "Midfielder" },
  { name: "Casemiro", team: "Manchester United", position: "Midfielder" },
  { name: "Gerson", team: "Flamengo", position: "Midfielder" },
  { name: "Lucas Paqueta", team: "West Ham United", position: "Midfielder" },
  { name: "Matheus Pereira", team: "Cruzeiro", position: "Midfielder" },
  { name: "Joelinton", team: "Newcastle United", position: "Midfielder" },
  { name: "Raphael Veiga", team: "Palmeiras", position: "Midfielder" },
  { name: "Mauricio", team: "Palmeiras", position: "Midfielder" },
  { name: "Alan Patrick", team: "Internacional", position: "Midfielder" },
  { name: "Gustavo Scarpa", team: "Atletico Mineiro", position: "Midfielder" },
  { name: "Otavio", team: "Atletico Mineiro", position: "Midfielder" },
  { name: "Andreas Pereira", team: "Fulham", position: "Midfielder" },
  { name: "Ederson", team: "Atalanta", position: "Midfielder" },
  { name: "Gabriel Sara", team: "Galatasaray", position: "Midfielder" },
  {
    name: "Gabriel Moscardo",
    team: "Paris Saint-Germain",
    position: "Midfielder",
  },
  { name: "Breno Bidon", team: "Corinthians", position: "Midfielder" },
  { name: "Everton Ribeiro", team: "Bahia", position: "Midfielder" },
  { name: "Cauly", team: "Bahia", position: "Midfielder" },
  { name: "Philippe Coutinho", team: "Vasco da Gama", position: "Midfielder" },
  { name: "Oscar", team: "Shanghai Port", position: "Midfielder" },
  { name: "Neymar", team: "Santos", position: "Forward" },
  { name: "Vinicius Junior", team: "Real Madrid", position: "Forward" },
  { name: "Rodrygo", team: "Real Madrid", position: "Forward" },
  { name: "Raphinha", team: "Barcelona", position: "Forward" },
  { name: "Savinho", team: "Manchester City", position: "Forward" },
  { name: "Martinelli", team: "Arsenal", position: "Forward" },
  { name: "Endrick", team: "Real Madrid", position: "Forward" },
  { name: "Evanilson", team: "Bournemouth", position: "Forward" },
  { name: "Joao Pedro", team: "Brighton", position: "Forward" },
  { name: "Gabriel Jesus", team: "Arsenal", position: "Forward" },
  { name: "Pedro", team: "Flamengo", position: "Forward" },
  { name: "Richarlison", team: "Tottenham", position: "Forward" },
  { name: "Matheus Cunha", team: "Wolverhampton", position: "Forward" },
  { name: "Igor Thiago", team: "Brentford", position: "Forward" },
  { name: "Estevao", team: "Palmeiras", position: "Forward" },
  { name: "Rayan", team: "Vasco da Gama", position: "Forward" },
  { name: "Marcos Leonardo", team: "Al Hilal", position: "Forward" },
  { name: "Malcom", team: "Al Hilal", position: "Forward" },
  { name: "Antony", team: "Manchester United", position: "Forward" },
  { name: "David Neres", team: "Napoli", position: "Forward" },
  { name: "Galeno", team: "Al Ahli", position: "Forward" },
  { name: "Everton Cebolinha", team: "Flamengo", position: "Forward" },
  { name: "Luiz Araujo", team: "Flamengo", position: "Forward" },
  { name: "Hulk", team: "Atletico Mineiro", position: "Forward" },
  { name: "Paulinho", team: "Palmeiras", position: "Forward" },
  { name: "Vitor Roque", team: "Palmeiras", position: "Forward" },
  { name: "Kaio Jorge", team: "Cruzeiro", position: "Forward" },
  { name: "Yuri Alberto", team: "Corinthians", position: "Forward" },
  { name: "Samuel Lino", team: "Atletico Madrid", position: "Forward" },
  { name: "Pepe", team: "Porto", position: "Forward" },
  { name: "Tete", team: "Panathinaikos", position: "Forward" },
  { name: "Willian", team: "Fulham", position: "Forward" },
  { name: "Dudu", team: "Cruzeiro", position: "Forward" },
  { name: "Lucas Moura", team: "Sao Paulo", position: "Forward" },
  { name: "Bruno Henrique", team: "Flamengo", position: "Forward" },
  { name: "Rony", team: "Atletico Mineiro", position: "Forward" },
  { name: "Luciano", team: "Sao Paulo", position: "Forward" },
  { name: "Igor Jesus", team: "Botafogo", position: "Forward" },
  { name: "Artur", team: "Botafogo", position: "Forward" },
];
